# Site settings
title:  Robin
email: robin_yhzheng@126.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: All work and no play makes jack a dull boy

gems: [jekyll-paginate]

paginate: 5
paginate_path: "blog/page:num"

#pagin
paginate: 5
# Social icons
facebook: YuhangZheng
linkedin: YuhangZheng
github: robin-yhzheng
deviantart: username
codepen: username

footer: © Robin


# Build settings
markdown: kramdown
